
name: Deploy to Production GCP


on:
  push:
    branches:
      - main

jobs:
  deploy:
    
    name: Deploy Application
   
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

     
      - name: Install Dependencies and Lint
        run: |
          npm install
          npm run lint

      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v1.0.3
        with:
         
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
 
          script: |
            echo "---  Successfully connected to server ---"
            
            # Navigate to the project folder on the VM.
            cd ~/udaipur-eco-action-hub
            
            # Pull the latest code changes from your GitHub repository.
            echo "---  Pulling latest code from main branch ---"
            git pull origin main
            
            # Rebuild the Docker image using the Dockerfile.
            echo "---   Rebuilding Docker image: eco-earth-app ---"
            docker build -t eco-earth-app .
            
            # Stop and remove the old container.
            echo "---  Stopping and removing old container ---"
            (docker stop eco-earth-container && docker rm eco-earth-container) || echo "Container not found, creating a new one."
            
         
            echo "---  Launching new container ---"
            docker run -d --name eco-earth-container --restart always -p 80:80 -p 443:443 -v /etc/letsencrypt:/etc/letsencrypt:ro eco-earth-app
            
            
            echo "---  Deployment to Production Complete ---"
